api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    
    enable_docs: true  
    enable_swagger_ui: true 

    swagger:
        versions: [3]  
        api_keys:
            - name: Authorization
              type: header  

    title: 'API Biblio'
    version: '3.0.0'
